branch-defaults:
  main:
    environment: rseg176a1v7-env
    group_suffix: null
environment-defaults:
  rseg176-a1-env:
    branch: null
    repository: null
global:
  application_name: rseg176a1v7
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.8
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
